spring.application.name=demo

# Supabase connection
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&user=postgres.fsjwchaiaprjaojgdagy
spring.datasource.username=postgres.fsjwchaiaprjaojgdagy
spring.datasource.password=cst438passwo
spring.datasource.driver-class-name=org.postgresql.Driver

# fixes "prepared statement already exists" error with Supabase connection pooling
spring.datasource.hikari.connection-init-sql=DEALLOCATE ALL

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# directing spring security to supabase for authentication endpoint
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://yoazzajeriqpcvolofyu.supabase.co/auth/v1/keys